"""initial schema

Full DDL per docs/02_Database.md: all 30 tables, native enum types,
soft-delete-aware partial unique indexes, pg_trgm fuzzy-search indexes,
the set_updated_at() trigger (§5), and monthly RANGE(created_at)
partitioning for the append-only tables (§9): inventory_movements,
audit_logs, cash_ledger, bank_ledger. Autogenerated table/index bodies,
hand-edited for everything autogenerate cannot express.

Revision ID: 1eca2cb3e208
Revises:
Create Date: 2026-07-25 15:23:23.257779

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1eca2cb3e208"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _enum_types() -> "list[postgresql.ENUM]":
    # Created explicitly (checkfirst) because ledger_entry_type is used by
    # two tables -- inline creation inside create_table would CREATE TYPE
    # twice and fail; every inline use below has create_type=False.
    return [
        postgresql.ENUM("owner", "staff", "viewer", name="user_role"),
        postgresql.ENUM("weight", "count", "length", "volume", name="unit_kind"),
        postgresql.ENUM("draft", "confirmed", "cancelled", name="purchase_status"),
        postgresql.ENUM("cash", "bank", "credit", name="sale_payment_type"),
        postgresql.ENUM(
            "purchase",
            "purchase_return",
            "sale",
            "sale_return",
            "adjustment_increase",
            "adjustment_decrease",
            "damage",
            "transfer_in",
            "transfer_out",
            name="movement_type",
        ),
        postgresql.ENUM(
            "purchase_payment",
            "sale_receipt",
            "expense",
            "income",
            "capital_in",
            "capital_out",
            "transfer_to_bank",
            "transfer_to_cash",
            "opening_balance",
            name="ledger_entry_type",
        ),
        postgresql.ENUM(
            "contribution", "withdrawal", "profit_allocation", name="capital_entry_type"
        ),
    ]


# every table carrying an updated_at column -- docs/02_Database.md §5
_UPDATED_AT_TABLES = (
    "organizations",
    "users",
    "partners",
    "suppliers",
    "customers",
    "products",
    "ocr_templates",
    "ocr_learning_dictionary",
    "purchase_headers",
    "sales_headers",
    "inventory",
    "expenses",
    "income",
    "whatsapp_sessions",
    "settings",
)

# append-only, partitioned by month -- docs/02_Database.md §9
_PARTITIONED_TABLES = ("inventory_movements", "audit_logs", "cash_ledger", "bank_ledger")


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    bind = op.get_bind()
    for enum_type in _enum_types():
        enum_type.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("base_currency", sa.CHAR(length=3), server_default="INR", nullable=False),
        sa.Column("timezone", sa.String(), server_default="Asia/Kolkata", nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "brands",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_brands_org_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
    )
    op.create_index(
        "brands_org_name_active_uq",
        "brands",
        ["org_id", "name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(op.f("ix_brands_org_id"), "brands", ["org_id"], unique=False)
    op.create_table(
        "product_categories",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_product_categories_org_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["product_categories.id"],
            name=op.f("fk_product_categories_parent_id_product_categories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_categories")),
        sa.UniqueConstraint(
            "org_id",
            "name",
            "parent_id",
            name=op.f("uq_product_categories_org_id_name_parent_id"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        op.f("ix_product_categories_org_id"), "product_categories", ["org_id"], unique=False
    )
    op.create_table(
        "units",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "weight", "count", "length", "volume", name="unit_kind", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_units_org_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units")),
        sa.UniqueConstraint("org_id", "code", name=op.f("uq_units_org_id_code")),
    )
    op.create_index(op.f("ix_units_org_id"), "units", ["org_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("whatsapp_number", sa.String(), nullable=True),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column(
            "role",
            postgresql.ENUM("owner", "staff", "viewer", name="user_role", create_type=False),
            server_default="staff",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "whatsapp_number IS NOT NULL OR email IS NOT NULL", name=op.f("ck_users_login_method")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_users_org_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_org_id"), "users", ["org_id"], unique=False)
    op.create_index(
        "users_email_active_uq",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "users_whatsapp_number_active_uq",
        "users",
        ["whatsapp_number"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "warehouses",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_warehouses_org_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouses")),
        sa.UniqueConstraint("org_id", "name", name=op.f("uq_warehouses_org_id_name")),
    )
    op.create_index(op.f("ix_warehouses_org_id"), "warehouses", ["org_id"], unique=False)
    op.create_index(
        "warehouses_one_default_per_org",
        "warehouses",
        ["org_id"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    op.create_table(
        "attachments",
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256_hash", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="uploaded", nullable=False),
        sa.Column("ocr_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("whatsapp_media_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('uploaded','processing','processed','failed')",
            name=op.f("ck_attachments_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_attachments_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_attachments_org_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
    )
    op.create_index(op.f("ix_attachments_org_id"), "attachments", ["org_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("before_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("whatsapp_message_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "channel IN ('whatsapp','api','dashboard','system')",
            name=op.f("ck_audit_logs_channel_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_audit_logs_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_audit_logs_org_id_organizations")
        ),
        sa.PrimaryKeyConstraint("created_at", "id", name=op.f("pk_audit_logs")),
        postgresql_partition_by="RANGE (created_at)",
    )
    op.create_index(
        "idx_audit_logs_org_created", "audit_logs", ["org_id", "created_at"], unique=False
    )
    op.create_index(
        "idx_audit_logs_org_entity",
        "audit_logs",
        ["org_id", "entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(op.f("ix_audit_logs_org_id"), "audit_logs", ["org_id"], unique=False)
    op.create_table(
        "bank_ledger",
        sa.Column(
            "entry_type",
            postgresql.ENUM(
                "purchase_payment",
                "sale_receipt",
                "expense",
                "income",
                "capital_in",
                "capital_out",
                "transfer_to_bank",
                "transfer_to_cash",
                "opening_balance",
                name="ledger_entry_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("resulting_balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("entry_date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_bank_ledger_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_bank_ledger_org_id_organizations")
        ),
        sa.PrimaryKeyConstraint("created_at", "id", name=op.f("pk_bank_ledger")),
        postgresql_partition_by="RANGE (created_at)",
    )
    op.create_index(
        "idx_bank_ledger_org_date", "bank_ledger", ["org_id", "entry_date"], unique=False
    )
    op.create_index(op.f("ix_bank_ledger_org_id"), "bank_ledger", ["org_id"], unique=False)
    op.create_table(
        "cash_ledger",
        sa.Column(
            "entry_type",
            postgresql.ENUM(
                "purchase_payment",
                "sale_receipt",
                "expense",
                "income",
                "capital_in",
                "capital_out",
                "transfer_to_bank",
                "transfer_to_cash",
                "opening_balance",
                name="ledger_entry_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("resulting_balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("entry_date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_cash_ledger_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_cash_ledger_org_id_organizations")
        ),
        sa.PrimaryKeyConstraint("created_at", "id", name=op.f("pk_cash_ledger")),
        postgresql_partition_by="RANGE (created_at)",
    )
    op.create_index(
        "idx_cash_ledger_org_date", "cash_ledger", ["org_id", "entry_date"], unique=False
    )
    op.create_index(op.f("ix_cash_ledger_org_id"), "cash_ledger", ["org_id"], unique=False)
    op.create_table(
        "customers",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("gst_number", sa.String(), nullable=True),
        sa.Column("credit_limit", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column(
            "opening_balance",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_customers_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_customers_org_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.create_index(
        "customers_org_name_active_uq",
        "customers",
        ["org_id", "name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "idx_customers_name_trgm",
        "customers",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_customers_org_id"), "customers", ["org_id"], unique=False)
    op.create_table(
        "income",
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("received_via", sa.String(), nullable=False),
        sa.Column("income_date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "received_via IN ('cash','bank')", name=op.f("ck_income_received_via_valid")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_income_amount_positive")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_income_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_income_org_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_income")),
    )
    op.create_index(op.f("ix_income_org_id"), "income", ["org_id"], unique=False)
    op.create_table(
        "journal",
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_journal_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_journal_org_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal")),
    )
    op.create_index(op.f("ix_journal_org_id"), "journal", ["org_id"], unique=False)
    op.create_table(
        "partners",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("profit_share_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_partners_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_partners_org_id_organizations")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_partners_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_partners")),
    )
    op.create_index(op.f("ix_partners_org_id"), "partners", ["org_id"], unique=False)
    op.create_table(
        "product_types",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("default_unit_id", sa.UUID(), nullable=False),
        sa.Column(
            "costing_strategy", sa.String(), server_default="weighted_average", nullable=False
        ),
        sa.Column(
            "attribute_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "costing_strategy IN ('weighted_average')",
            name=op.f("ck_product_types_costing_strategy_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["default_unit_id"], ["units.id"], name=op.f("fk_product_types_default_unit_id_units")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_product_types_org_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_types")),
        sa.UniqueConstraint("org_id", "code", name=op.f("uq_product_types_org_id_code")),
    )
    op.create_index(op.f("ix_product_types_org_id"), "product_types", ["org_id"], unique=False)
    op.create_table(
        "settings",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_settings_org_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_settings_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
        sa.UniqueConstraint("org_id", "key", name=op.f("uq_settings_org_id_key")),
    )
    op.create_index(op.f("ix_settings_org_id"), "settings", ["org_id"], unique=False)
    op.create_table(
        "suppliers",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("gst_number", sa.String(), nullable=True),
        sa.Column(
            "opening_balance",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_suppliers_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_suppliers_org_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
    )
    op.create_index(
        "idx_suppliers_name_trgm",
        "suppliers",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_suppliers_org_id"), "suppliers", ["org_id"], unique=False)
    op.create_index(
        "suppliers_org_name_active_uq",
        "suppliers",
        ["org_id", "name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "whatsapp_sessions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_whatsapp_sessions_org_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_whatsapp_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_whatsapp_sessions")),
        sa.UniqueConstraint("org_id", "user_id", name=op.f("uq_whatsapp_sessions_org_id_user_id")),
    )
    op.create_index(
        op.f("ix_whatsapp_sessions_org_id"), "whatsapp_sessions", ["org_id"], unique=False
    )
    op.create_table(
        "expenses",
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("paid_via", sa.String(), nullable=False),
        sa.Column("paid_by_partner_id", sa.UUID(), nullable=True),
        sa.Column(
            "expense_date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False
        ),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("attachment_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("paid_via IN ('cash','bank')", name=op.f("ck_expenses_paid_via_valid")),
        sa.CheckConstraint("amount > 0", name=op.f("ck_expenses_amount_positive")),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            ["attachments.id"],
            name=op.f("fk_expenses_attachment_id_attachments"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_expenses_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_expenses_org_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["paid_by_partner_id"],
            ["partners.id"],
            name=op.f("fk_expenses_paid_by_partner_id_partners"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expenses")),
    )
    op.create_index(op.f("ix_expenses_org_id"), "expenses", ["org_id"], unique=False)
    op.create_table(
        "journal_lines",
        sa.Column("journal_id", sa.UUID(), nullable=False),
        sa.Column("account_code", sa.String(), nullable=False),
        sa.Column(
            "debit", sa.Numeric(precision=14, scale=2), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "credit", sa.Numeric(precision=14, scale=2), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "(debit = 0) <> (credit = 0)", name=op.f("ck_journal_lines_exactly_one_side")
        ),
        sa.CheckConstraint("credit >= 0", name=op.f("ck_journal_lines_credit_non_negative")),
        sa.CheckConstraint("debit >= 0", name=op.f("ck_journal_lines_debit_non_negative")),
        sa.ForeignKeyConstraint(
            ["journal_id"], ["journal.id"], name=op.f("fk_journal_lines_journal_id_journal")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_lines")),
    )
    op.create_table(
        "ocr_learning_dictionary",
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("field", sa.String(), nullable=False),
        sa.Column("raw_ocr_text", sa.String(), nullable=False),
        sa.Column("corrected_value", sa.String(), nullable=False),
        sa.Column("hit_count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_ocr_learning_dictionary_org_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_ocr_learning_dictionary_supplier_id_suppliers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ocr_learning_dictionary")),
        sa.UniqueConstraint(
            "org_id",
            "supplier_id",
            "field",
            "raw_ocr_text",
            name=op.f("uq_ocr_learning_dictionary_org_id_supplier_id_field_raw_ocr_text"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "idx_ocr_learning_raw_trgm",
        "ocr_learning_dictionary",
        ["raw_ocr_text"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"raw_ocr_text": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_ocr_learning_dictionary_org_id"),
        "ocr_learning_dictionary",
        ["org_id"],
        unique=False,
    )
    op.create_table(
        "ocr_templates",
        sa.Column("product_type_id", sa.UUID(), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("column_mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "ignore_columns",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text('\'["s.no","label","total"]\'::jsonb'),
            nullable=False,
        ),
        sa.Column(
            "required_manual_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text(
                '\'["supplier","brand","invoice_no","invoice_date","purchase_rate","freight","other_charges"]\'::jsonb'
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_ocr_templates_org_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["product_type_id"],
            ["product_types.id"],
            name=op.f("fk_ocr_templates_product_type_id_product_types"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.id"], name=op.f("fk_ocr_templates_supplier_id_suppliers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ocr_templates")),
        sa.UniqueConstraint(
            "org_id",
            "product_type_id",
            "supplier_id",
            name=op.f("uq_ocr_templates_org_id_product_type_id_supplier_id"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(op.f("ix_ocr_templates_org_id"), "ocr_templates", ["org_id"], unique=False)
    op.create_table(
        "partner_capital",
        sa.Column("partner_id", sa.UUID(), nullable=False),
        sa.Column(
            "entry_type",
            postgresql.ENUM(
                "contribution",
                "withdrawal",
                "profit_allocation",
                name="capital_entry_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("resulting_balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("settled_via", sa.String(), nullable=True),
        sa.Column("entry_date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column(
            "approved_by_partner_ids",
            postgresql.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'::uuid[]"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "settled_via IN ('cash','bank')", name=op.f("ck_partner_capital_settled_via_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_partner_capital_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_partner_capital_org_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"], ["partners.id"], name=op.f("fk_partner_capital_partner_id_partners")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_partner_capital")),
    )
    op.create_index(op.f("ix_partner_capital_org_id"), "partner_capital", ["org_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("product_type_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("reorder_level", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_products_brand_id_brands")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["product_categories.id"],
            name=op.f("fk_products_category_id_product_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_products_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_products_org_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["product_type_id"],
            ["product_types.id"],
            name=op.f("fk_products_product_type_id_product_types"),
        ),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], name=op.f("fk_products_unit_id_units")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(
        "idx_products_code_trgm",
        "products",
        ["code"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"code": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_products_description_trgm",
        "products",
        ["description"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_products_org_brand",
        "products",
        ["org_id", "brand_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "idx_products_org_type",
        "products",
        ["org_id", "product_type_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(op.f("ix_products_org_id"), "products", ["org_id"], unique=False)
    op.create_index(
        "products_org_code_active_uq",
        "products",
        ["org_id", sa.literal_column("upper(code)")],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "purchase_headers",
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=True),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("invoice_no", sa.String(), nullable=False),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("purchase_rate", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column(
            "freight",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "other_charges",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "freight_allocation_method", sa.String(), server_default="by_weight", nullable=False
        ),
        sa.Column(
            "subtotal",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "grand_total",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("declared_total", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft", "confirmed", "cancelled", name="purchase_status", create_type=False
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("payment_status", sa.String(), server_default="unpaid", nullable=False),
        sa.Column(
            "amount_paid",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("ocr_source_attachment_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "freight_allocation_method IN ('by_weight','by_value','by_qty','manual')",
            name=op.f("ck_purchase_headers_freight_allocation_method_valid"),
        ),
        sa.CheckConstraint(
            "payment_status IN ('unpaid','partial','paid')",
            name=op.f("ck_purchase_headers_payment_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_purchase_headers_brand_id_brands")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_purchase_headers_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["ocr_source_attachment_id"],
            ["attachments.id"],
            name=op.f("fk_purchase_headers_ocr_source_attachment_id_attachments"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_purchase_headers_org_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_purchase_headers_supplier_id_suppliers"),
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_purchase_headers_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_headers")),
    )
    op.create_index(
        "idx_purchase_headers_dup_check",
        "purchase_headers",
        ["org_id", "supplier_id", "invoice_date", "grand_total"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "idx_purchase_headers_org_date",
        "purchase_headers",
        ["org_id", "invoice_date"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "idx_purchase_headers_org_supplier",
        "purchase_headers",
        ["org_id", "supplier_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_purchase_headers_org_id"), "purchase_headers", ["org_id"], unique=False
    )
    op.create_index(
        "purchase_headers_org_supplier_invoice_active_uq",
        "purchase_headers",
        ["org_id", "supplier_id", "invoice_no"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "sales_headers",
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("sale_date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False),
        sa.Column(
            "payment_type",
            postgresql.ENUM("cash", "bank", "credit", name="sale_payment_type", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "subtotal",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "grand_total",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "amount_paid",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("payment_status", sa.String(), server_default="unpaid", nullable=False),
        sa.Column("status", sa.String(), server_default="confirmed", nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "payment_status IN ('unpaid','partial','paid')",
            name=op.f("ck_sales_headers_payment_status_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('confirmed','cancelled','returned','partially_returned')",
            name=op.f("ck_sales_headers_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_sales_headers_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_sales_headers_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_sales_headers_org_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_sales_headers_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_headers")),
    )
    op.create_index(
        "idx_sales_headers_org_customer",
        "sales_headers",
        ["org_id", "customer_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "idx_sales_headers_org_date",
        "sales_headers",
        ["org_id", "sale_date"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(op.f("ix_sales_headers_org_id"), "sales_headers", ["org_id"], unique=False)
    op.create_index(
        "sales_headers_org_idempotency_active_uq",
        "sales_headers",
        ["org_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_table(
        "inventory",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column(
            "qty_on_hand",
            sa.Numeric(precision=12, scale=3),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "weighted_avg_cost",
            sa.Numeric(precision=12, scale=4),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_inventory_org_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_inventory_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"], ["warehouses.id"], name=op.f("fk_inventory_warehouse_id_warehouses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory")),
        sa.UniqueConstraint(
            "org_id",
            "product_id",
            "warehouse_id",
            name=op.f("uq_inventory_org_id_product_id_warehouse_id"),
        ),
    )
    op.create_index(op.f("ix_inventory_org_id"), "inventory", ["org_id"], unique=False)
    op.create_table(
        "inventory_movements",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column(
            "movement_type",
            postgresql.ENUM(
                "purchase",
                "purchase_return",
                "sale",
                "sale_return",
                "adjustment_increase",
                "adjustment_decrease",
                "damage",
                "transfer_in",
                "transfer_out",
                name="movement_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("qty_delta", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("resulting_qty_on_hand", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("resulting_avg_cost", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_inventory_movements_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_inventory_movements_org_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_inventory_movements_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_movements_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("created_at", "id", name=op.f("pk_inventory_movements")),
        postgresql_partition_by="RANGE (created_at)",
    )
    op.create_index(
        "idx_inventory_movements_product_warehouse",
        "inventory_movements",
        ["org_id", "product_id", "warehouse_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_inventory_movements_source",
        "inventory_movements",
        ["source_type", "source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_org_id"), "inventory_movements", ["org_id"], unique=False
    )
    op.create_table(
        "purchase_lines",
        sa.Column("purchase_header_id", sa.UUID(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("total_weight_kg", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("rate", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "freight_allocated",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("landed_cost_per_unit", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("ocr_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("qty > 0", name=op.f("ck_purchase_lines_qty_positive")),
        sa.CheckConstraint("rate >= 0", name=op.f("ck_purchase_lines_rate_non_negative")),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_purchase_lines_org_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_purchase_lines_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["purchase_header_id"],
            ["purchase_headers.id"],
            name=op.f("fk_purchase_lines_purchase_header_id_purchase_headers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_lines")),
        sa.UniqueConstraint(
            "purchase_header_id",
            "line_no",
            name=op.f("uq_purchase_lines_purchase_header_id_line_no"),
        ),
    )
    op.create_index(
        "idx_purchase_lines_header", "purchase_lines", ["purchase_header_id"], unique=False
    )
    op.create_index("idx_purchase_lines_product", "purchase_lines", ["product_id"], unique=False)
    op.create_index(op.f("ix_purchase_lines_org_id"), "purchase_lines", ["org_id"], unique=False)
    op.create_table(
        "sales_lines",
        sa.Column("sales_header_id", sa.UUID(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("avg_cost_at_sale_time", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "returned_qty",
            sa.Numeric(precision=12, scale=3),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("qty > 0", name=op.f("ck_sales_lines_qty_positive")),
        sa.CheckConstraint("rate >= 0", name=op.f("ck_sales_lines_rate_non_negative")),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_sales_lines_org_id_organizations")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_sales_lines_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["sales_header_id"],
            ["sales_headers.id"],
            name=op.f("fk_sales_lines_sales_header_id_sales_headers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_lines")),
        sa.UniqueConstraint(
            "sales_header_id", "line_no", name=op.f("uq_sales_lines_sales_header_id_line_no")
        ),
    )
    op.create_index("idx_sales_lines_header", "sales_lines", ["sales_header_id"], unique=False)
    op.create_index("idx_sales_lines_product", "sales_lines", ["product_id"], unique=False)
    op.create_index(op.f("ix_sales_lines_org_id"), "sales_lines", ["org_id"], unique=False)
    # ### end Alembic commands ###

    # updated_at bumped by trigger, not application code -- §5
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    for table in _UPDATED_AT_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table}_updated_at BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
        )

    # Monthly partitions -- §9. The helper is kept in the database so the
    # scheduled partition-maintenance worker (docs/11_BackgroundWorkers.md)
    # can extend the horizon; the DEFAULT partition guarantees an insert
    # never fails even if maintenance lapses.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION create_month_partitions(
            parent text, from_month date, months integer
        ) RETURNS void AS $$
        DECLARE
            m date;
        BEGIN
            FOR i IN 0..months - 1 LOOP
                m := (from_month + make_interval(months => i))::date;
                EXECUTE format(
                    'CREATE TABLE IF NOT EXISTS %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
                    parent || '_' || to_char(m, 'YYYY_MM'),
                    parent,
                    m,
                    (m + interval '1 month')::date
                );
            END LOOP;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    for table in _PARTITIONED_TABLES:
        op.execute(
            f"SELECT create_month_partitions('{table}', date_trunc('month', now())::date, 13)"
        )
        op.execute(f"CREATE TABLE {table}_default PARTITION OF {table} DEFAULT")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sales_lines_org_id"), table_name="sales_lines")
    op.drop_index("idx_sales_lines_product", table_name="sales_lines")
    op.drop_index("idx_sales_lines_header", table_name="sales_lines")
    op.drop_table("sales_lines")
    op.drop_index(op.f("ix_purchase_lines_org_id"), table_name="purchase_lines")
    op.drop_index("idx_purchase_lines_product", table_name="purchase_lines")
    op.drop_index("idx_purchase_lines_header", table_name="purchase_lines")
    op.drop_table("purchase_lines")
    op.drop_index(op.f("ix_inventory_movements_org_id"), table_name="inventory_movements")
    op.drop_index("idx_inventory_movements_source", table_name="inventory_movements")
    op.drop_index("idx_inventory_movements_product_warehouse", table_name="inventory_movements")
    op.drop_table("inventory_movements")
    op.drop_index(op.f("ix_inventory_org_id"), table_name="inventory")
    op.drop_table("inventory")
    op.drop_index(
        "sales_headers_org_idempotency_active_uq",
        table_name="sales_headers",
        postgresql_where=sa.text("idempotency_key IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_sales_headers_org_id"), table_name="sales_headers")
    op.drop_index(
        "idx_sales_headers_org_date",
        table_name="sales_headers",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "idx_sales_headers_org_customer",
        table_name="sales_headers",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("sales_headers")
    op.drop_index(
        "purchase_headers_org_supplier_invoice_active_uq",
        table_name="purchase_headers",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_purchase_headers_org_id"), table_name="purchase_headers")
    op.drop_index(
        "idx_purchase_headers_org_supplier",
        table_name="purchase_headers",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "idx_purchase_headers_org_date",
        table_name="purchase_headers",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "idx_purchase_headers_dup_check",
        table_name="purchase_headers",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("purchase_headers")
    op.drop_index(
        "products_org_code_active_uq",
        table_name="products",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_products_org_id"), table_name="products")
    op.drop_index(
        "idx_products_org_type",
        table_name="products",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "idx_products_org_brand",
        table_name="products",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "idx_products_description_trgm",
        table_name="products",
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    op.drop_index(
        "idx_products_code_trgm",
        table_name="products",
        postgresql_using="gin",
        postgresql_ops={"code": "gin_trgm_ops"},
    )
    op.drop_table("products")
    op.drop_index(op.f("ix_partner_capital_org_id"), table_name="partner_capital")
    op.drop_table("partner_capital")
    op.drop_index(op.f("ix_ocr_templates_org_id"), table_name="ocr_templates")
    op.drop_table("ocr_templates")
    op.drop_index(op.f("ix_ocr_learning_dictionary_org_id"), table_name="ocr_learning_dictionary")
    op.drop_index(
        "idx_ocr_learning_raw_trgm",
        table_name="ocr_learning_dictionary",
        postgresql_using="gin",
        postgresql_ops={"raw_ocr_text": "gin_trgm_ops"},
    )
    op.drop_table("ocr_learning_dictionary")
    op.drop_table("journal_lines")
    op.drop_index(op.f("ix_expenses_org_id"), table_name="expenses")
    op.drop_table("expenses")
    op.drop_index(op.f("ix_whatsapp_sessions_org_id"), table_name="whatsapp_sessions")
    op.drop_table("whatsapp_sessions")
    op.drop_index(
        "suppliers_org_name_active_uq",
        table_name="suppliers",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_suppliers_org_id"), table_name="suppliers")
    op.drop_index(
        "idx_suppliers_name_trgm",
        table_name="suppliers",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("suppliers")
    op.drop_index(op.f("ix_settings_org_id"), table_name="settings")
    op.drop_table("settings")
    op.drop_index(op.f("ix_product_types_org_id"), table_name="product_types")
    op.drop_table("product_types")
    op.drop_index(op.f("ix_partners_org_id"), table_name="partners")
    op.drop_table("partners")
    op.drop_index(op.f("ix_journal_org_id"), table_name="journal")
    op.drop_table("journal")
    op.drop_index(op.f("ix_income_org_id"), table_name="income")
    op.drop_table("income")
    op.drop_index(op.f("ix_customers_org_id"), table_name="customers")
    op.drop_index(
        "idx_customers_name_trgm",
        table_name="customers",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(
        "customers_org_name_active_uq",
        table_name="customers",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("customers")
    op.drop_index(op.f("ix_cash_ledger_org_id"), table_name="cash_ledger")
    op.drop_index("idx_cash_ledger_org_date", table_name="cash_ledger")
    op.drop_table("cash_ledger")
    op.drop_index(op.f("ix_bank_ledger_org_id"), table_name="bank_ledger")
    op.drop_index("idx_bank_ledger_org_date", table_name="bank_ledger")
    op.drop_table("bank_ledger")
    op.drop_index(op.f("ix_audit_logs_org_id"), table_name="audit_logs")
    op.drop_index("idx_audit_logs_org_entity", table_name="audit_logs")
    op.drop_index("idx_audit_logs_org_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_attachments_org_id"), table_name="attachments")
    op.drop_table("attachments")
    op.drop_index(
        "warehouses_one_default_per_org",
        table_name="warehouses",
        postgresql_where=sa.text("is_default"),
    )
    op.drop_index(op.f("ix_warehouses_org_id"), table_name="warehouses")
    op.drop_table("warehouses")
    op.drop_index(
        "users_whatsapp_number_active_uq",
        table_name="users",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "users_email_active_uq", table_name="users", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_index(op.f("ix_users_org_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_units_org_id"), table_name="units")
    op.drop_table("units")
    op.drop_index(op.f("ix_product_categories_org_id"), table_name="product_categories")
    op.drop_table("product_categories")
    op.drop_index(op.f("ix_brands_org_id"), table_name="brands")
    op.drop_index(
        "brands_org_name_active_uq",
        table_name="brands",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("brands")
    op.drop_table("organizations")
    # ### end Alembic commands ###

    # partition children are dropped with their parents above
    op.execute("DROP FUNCTION IF EXISTS create_month_partitions(text, date, integer)")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
    bind = op.get_bind()
    for enum_type in _enum_types():
        enum_type.drop(bind, checkfirst=True)
